name: Print Changed Files

on:
  push:

jobs:
  print-changed-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Get Changed files
        id: get-changed-files
        run: |
          BEFORE="${{ github.event.before }}"
          AFTER="${{ github.sha }}"

          # ---------------------------------------------------------------
          # CASE 1 - First push on a brand-new branch (no previous commit)
          # ---------------------------------------------------------------
          if [[ "$BEFORE" == "0000000000000000000000000000000000000000" ]]; then
            echo "New branch detected — comparing against parent commit of the pushed commit."
            CHANGED_FILES=$(git diff --name-only "${AFTER}^")

          # ---------------------------------------------------------------
          # CASE 2 - Merge commit (two parents)
          # ---------------------------------------------------------------
          elif git rev-parse --verify "${AFTER}^2" > /dev/null 2>&1; then
            PARENT_1=$(git rev-parse "${AFTER}^1")
            PARENT_2=$(git rev-parse "${AFTER}^2")
            
            # ---------------------------------------------------------------
            # CASE 2.1 - Merge commit to Main
            # ---------------------------------------------------------------
            if [[ "${GITHUB_REF}" == 'refs/heads/main' ]]; then
              echo "Merge commit to main detected — diffing against parent1 (${PARENT_1}) and parent2 (${PARENT_2})"
              CHANGED_FILES=$(git diff --name-only "${PARENT_1}...${PARENT_2}")

            # ---------------------------------------------------------------
            # CASE 2.2 - Merge commit to a non-main branch
            # ---------------------------------------------------------------
            else
              echo "Merge commit to non-main branch detected — diffing against the merged commit (${AFTER}) and its parents (${PARENT_1} and ${PARENT_2})"
              CHANGED_FILES=$(git diff --name-only ${AFTER}^ "${AFTER}")
            fi

          # ---------------------------------------------------------------
          # CASE 3 - Regular push: diff previous commit against current HEAD
          # ---------------------------------------------------------------
          else
            echo "Regular push — diffing ${BEFORE} → ${AFTER}"
            CHANGED_FILES=$(git diff --name-only "${BEFORE}" "${AFTER}")
          fi

          CHANGED_FILES_LIST=$(echo "$CHANGED_FILES" | awk '{printf "%s%s", sep, $0; sep=" , "}')
          echo "Files changed: $CHANGED_FILES_LIST"

          echo "files=$CHANGED_FILES_LIST"
          echo "has_changed_files=$([ -z "$CHANGED_FILES_LIST" ] && echo "false" || echo "true")"

          if [[ -n "${{ inputs.ENVIRONMENT }}" ]]; then
            echo "override_placeholders=environment ${{ inputs.ENVIRONMENT }}"
          fi
